baseURL = 'https://thefishing.dev/'
languageCode = 'en-us'
title = 'The Fishing Dev'
theme = 'travelify'
canonifyURLs = true

[params]
    # Tell me who you are
    author = "thefishingdev"
    site_description = "A travel blog with some fishing trips sprinkled in"
    copyright  = "by The Fishing Dev."
    #avatar = "avatar.png"
    logo = "images/logo.png"
    logo_alt_txt = "A large-ish Mutton Snapper at a ~140-degree angle over a code editor background"
    title_in_logo = true # set to true if you want the title along with the logo
    disable_mathjax = true # set to true to disable MathJax

    # Format dates with Go's time formatting
    date_format = "02 January, 2006"

    # Add custom assets with their paths relative to the static folder
    custom_css = []
    custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.

[[menu.main]]
    name  = "About"
    url   = "/about/"
    weight = 10

[[menu.main]]
    name  = "Contact"
    url   = "/contact/"
    weight = 20

[params.share]
    enable = false
    facebook = false
    twitter = false
    linkedin = false
    email = false

[params.privacy]
    enable = true # false implies switching on tracking application, you can individually turn off applications that you don't want. If enable = true, then all tracking apps are switched off
    facebook_like = false
    DisqusShortname = ""

[params.social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    rss             = "Needed" # leave this to blank if you do not want RSS feed icon to appear on top
    github          = "vt0r"
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    tumblr          = ""
    linkedin        = "salvatorelamendola"
    pinterest       = ""
    facebook        = ""
    twitter         = ""
    bluesky         = "thefishing.dev"
    mastodon_user   = "vt0r"
    mastodon_server = "ohai.social"
    keyoxide        = "4b5fd875f30c8cf39191b11dead217668b7336d5"
    email           = "contact@thefishing.dev"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true
    archives = false # This feature is yet to be implemented because of limitations in Hugo's way of working.
    search = false
    mailchimp = false
    #mailchimpform = ""
    author = true

[params.slider]
    enable = true
    manual = false # Setting manual to true renders the slide selection to only those where the post has a slider=true option enabled
    num_features = 6 # The slider picks up the banner images from the N most recent posts, where num_features is N.

[permalinks]
    categories = "/categories/:slug/" #can be changed to "/category/:slug/"
    tags = "/tags/:slug/"

[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"
    author = "author"

[params.views]
    enable = false  # visitor badge from https://visitor-badge.glitch.me/
